services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: kubsu
      POSTGRES_USER: kubsu
      POSTGRES_PASSWORD: kubsu
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "60080:60080"
    depends_on:
      - db
    env_file:
      - .env