name: Docker CI/CD

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Build the Docker image and Publish
      run: |
        tree
        docker build .

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./docker/Dockerfile
        push: false  
        tags: your-image-name:latest

    - name: Run tests
      run: |
        docker-compose -f docker/docker-compose.yml up -d
        docker-compose -f docker/docker-compose.yml exec -T app pytest tests/
